import { readFileSync, writeFileSync } from "node:fs";
const tokens = JSON.parse(
  readFileSync(
    new URL("../packages/design-tokens/happyhands.json", import.meta.url),
    "utf8",
  ),
);
const css =
  "/* Generated by scripts/brand-tokens.mjs. Source: supplied HappyHands design system; sans-serif override requested by user. */\n" +
  Object.entries(tokens)
    .map(
      ([mode, values]) =>
        `${mode === "light" ? ":root, " : ""}:root[data-hh-theme="${mode}"], :root[data-theme="${mode}"] {\n${Object.entries(
          values,
        )
          .map(([k, v]) => `  --hh-${k}: ${v};`)
          .join("\n")}\n}`,
    )
    .join("\n");
writeFileSync(
  new URL("../packages/design-tokens/happyhands.css", import.meta.url),
  css,
);
