const escapeHtml = value => String(value).replace(/[&<>"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char]);
export function sectionHead(kicker, title, copy, action = '') { return `<div class="section-head"><div><p class="kicker">${escapeHtml(kicker)}</p><h2>${title}</h2></div><div><p>${escapeHtml(copy)}</p>${action}</div></div>`; }
export function appCard(item) { return `<article class="app-card"><div class="card-top"><span>${item.index}</span><span class="state">${item.state}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p><ul>${item.meta.map(value => `<li>${escapeHtml(value)}</li>`).join('')}</ul><a href="${item.href}">${escapeHtml(item.action)} <span aria-hidden="true">↗</span></a></article>`; }
export function systemCard(item) { return `<article class="system-card"><div class="system-preview">${item.values.map((value, index) => `<span style="--i:${index}">${escapeHtml(value)}</span>`).join('')}</div><p class="card-tag">${escapeHtml(item.tag)}</p><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p><div class="chips">${item.traits.map(value => `<span>${escapeHtml(value)}</span>`).join('')}</div><a class="card-link" href="${item.href}">Explore system ↗</a></article>`; }
export function screenCard(item) { return `<figure class="screen-card"><div class="screen-image"><img src="${item.src}" alt="${escapeHtml(item.caption)}" loading="lazy"></div><figcaption><span>${escapeHtml(item.label)}</span><p>${escapeHtml(item.caption)}</p></figcaption></figure>`; }
export function screenPair(item) { return `<article class="screen-pair"><div class="pair-head"><div><p class="card-tag">${escapeHtml(item.task)}</p><h3>${escapeHtml(item.title)}</h3></div><span>${escapeHtml(item.result)}</span></div><div class="pair-images"><figure><span>BEFORE</span><img src="${item.before.src}" alt="${escapeHtml(item.before.caption)}" loading="lazy"></figure><div class="pair-arrow" aria-hidden="true">→</div><figure><span>AFTER</span><img src="${item.after.src}" alt="${escapeHtml(item.after.caption)}" loading="lazy"></figure></div></article>`; }
const previews = { button: `<div class="element-demo demo-buttons"><button>Run review</button><button>View evidence</button><button disabled>Publishing</button></div>`, input: `<div class="element-demo demo-input"><label>Repository URL</label><div>github.com/your/product <span>READY</span></div></div>`, status: `<div class="element-demo demo-status"><span>OBSERVED</span><span>CANDIDATE</span><span>APPROVED</span></div>`, tokens: `<div class="element-demo demo-tokens"><i></i><i></i><i></i><i></i><i></i></div>`, tabs: `<div class="element-demo demo-tabs"><span>Diagnose</span><span>Foundation</span><span>Visual QA</span></div>`, progress: `<div class="element-demo demo-progress"><span></span><span></span><span></span><span></span><span></span></div>`, empty: `<div class="element-demo demo-empty"><i>＋</i><strong>No reviews yet</strong><span>Connect a product to begin</span></div>`, dialog: `<div class="element-demo demo-dialog"><strong>Apply this direction?</strong><p>3 screens will be updated.</p><div><button>Cancel</button><button>Apply</button></div></div>`, card: `<div class="element-demo demo-card"><span>DESIGN FOUNDATION</span><strong>SaaS workspace</strong><p>12 tokens · 8 components</p><i>READY</i></div>` };
export function elementCard(item) { return `<article class="element-card">${previews[item.kind]}<p class="card-tag">UI ELEMENT</p><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p></article>`; }
export function stepCard(item) { return `<article class="step-card"><span>${item[0]}</span><h3>${escapeHtml(item[1])}</h3><p>${escapeHtml(item[2])}</p></article>`; }
